# Generated by Django 4.2.16 on 2024-10-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(default="", max_length=300),
        ),
    ]
